class Translation(object):

    HELP_TEXT = """<b><u>BASIC COMMANDS</u></b>\n\n • /start :- Check Iam Alive\n • /help :- More Details\n • /about :- About Me\n • /sub :- Support and deploy\n • /stats :- User Count""" 
    START_TEXT = """👋Hey {},𝗜  𝗔𝗠 𝗦𝗨𝗣𝗘𝗥 𝗔𝗨𝗧𝗢 𝗙𝗜𝗟𝗧𝗘𝗥 𝗕𝗢𝗧 𝗩𝟮..𝗜 𝗖𝗔𝗡 𝗣𝗿𝗼𝘃𝗶𝗱𝗲 𝗠𝗼𝘃𝗶𝗲𝘀 𝗜𝗻 𝗧𝗲𝗹𝗲𝗴𝗿𝗮𝗺 𝗚𝗿𝗼𝘂𝗽𝘀....

𝗝𝗨𝗦𝗧 𝗔𝗗𝗗 𝗠𝗘 𝗧𝗢 𝗬𝗢𝗨𝗥 𝗚𝗥𝗢𝗨𝗣 𝗪𝗜𝗧𝗛 𝗔𝗗𝗠𝗜𝗡 𝗥𝗜𝗚𝗛𝗧𝗦 𝗔𝗡𝗗 𝗘𝗡𝗝𝗢𝗬 𝗪𝗜𝗧𝗛 𝗠𝗔𝗡𝗬 𝗠𝗢𝗥𝗘 𝗙𝗘𝗔𝗧𝗨𝗥𝗘𝗦😍 

👨‍💻 𝗗𝗘𝗩𝗘𝗟𝗢𝗣𝗘𝗥 : \n\ᴇ𝗩ᴇ𝗟ᴏ𝗣ᴇ𝗥 : <a href="https://t.me/KOT_BOTS">Kᴏᴛ Bᴏᴛs</a> & <a href="https://t.me/KOT_FREE_DE_LA_HOYA_OFF">ҜᴏT ҒʀΣᴇ ᴅΣ ʟΔ ʜΩyΔ ᴏҒꜰ</a>"""       
    ABOUT_TEXT = """📃Bot : <a href="t.me/KOT_MOVIES_FILTER_BOT">Tʜᴀʟᴀᴘᴀᴛʜʏ Vɪᴊᴀʏ</a>\n🧒Dev : <a href="t.me/KOT_FREE_DE_LA_HOYA_OFF">ҜᴏT ҒʀΣᴇ ᴅΣ ʟΔ ʜΩyΔ ᴏҒꜰ</a>\n🧒Creator : <a href="t.me/KOT_BOTS">Kᴏᴛ Bᴏᴛs</a>\n📡Hosted On : <a href="https://heroku.com/">Hᴇʀᴏᴋᴜ</a>\n🗣️Language : <a href="https://docs.pyrogram.org">PYROGRAM</a>\n📚Library : <a href="https://docs.pyrogram.org">Pyrogram Asyncio 1.13.0 </a>\n🗒️Version : <a href="t.me/KOT_MOVIES_FILTER_BOT">2.9.0</a>\n📖Source Code : 🤐"""
    FSUB_TEXT = """ഹേയ് {} തായേ കാണുന്ന ചാനലിൽ നിങ്ങൾ ഇല്ല അത് കൊണ്ട് നിങ്ങൾക് സിനിമ കിട്ടില്ല...\nസിനിമ കിട്ടാനായി താഴെ കാണുന്ന 🔔 Join എന്ന ബട്ടനിൽ ക്ലിക്ക് ചെയ്തു ഞങ്ങളുടെ മെയിൻ ചാനലിൽ ജോയിൻ ചെയ്യുക എങ്കിൽ മാത്രമേ നിങ്ങൾക്ക് മൂവി ഈ ബോട്ട് വഴി ലഭിക്കുകയുള്ളു. അതു കഴ്ഞ്ഞു തായേ കാണുന്ന 👉"Try again"👈 എന്നുള്ളതിൽ ക്ലിക്ക് ചെയ്തു Start കൊടുത്താൽ നിങ്ങൾക്ക് മൂവി കിട്ടുന്നതാണ്.😁"""
    FILTER_TEXT = """<b><u>Manual Filter</u></b>\n\n• Add me as admin in your group and start filtering:\n\n<b><u>NOTE:</u></b>\n\n1. DonLee should have admin privillage.\n2. only admins can add filters in a chat.\n3. alert buttons have a limit of 64 characters.\n\n<b><u>Commands and Usage:</u></b>\n• /addfilter - Add filter for name\n• /filters - List all filters in chat\n• /delfilters - Delete filter\n• /delallfilters - Delete entire filters (Group Owner Only!) @KOT_BOTS"""
    AUTOFILTER_TEXT = """<b><u>Auto Filter</u></b>\n\n<b><u>🤖 Bot Commands 🤖</u></b>\n  <code>(Works Only In Groups):</code>\n\n<b><u>Add CMD</u></b>\n  ☞ <code>/addchannel</code> <b>chat_id</b>\n  ☞ <code>/addchannel</code> <b>@KOT_BOTS</b>\n<b>- To Connect A Group With A Channel (Bot Should Be Admin With Full Previlages In Both Group And Channel)</b>\n\n<b><u>Deleted CMD</u></b>\n  ☞ <code>/delchannel</code> <b>chat_id</b>\n  ☞ <code>/delchannel</code> <b>@KOT_BOTS</b>\n<b>- To disconnect A Group With A Channel</i></b> @KOT_BOTS"""
    AUTOFILTER_TEXT2 = """<b><u>📃 MAIN INFORMATION 📃</u></b>\n\n  ☞ <b>/settings</b> -  <b>This Command Will Display You A Settings Pannel Instance Which Can Be Used To Tweek Bot's Settings Accordingly</b>\n\n  ☞ <b>Channel</b> - <b>Button Will Show You All The Connected Chats With The Group And Will Show Buttons Correspnding To There Order For Furthur Controls</b>\n\n  ☞ <b>Filter Types</b> - <b>Button Will Show You The 3 Filter Option Available In Bot... Pressing Each Buttons Will Either Enable or Disable Them And This Will Take Into Action As Soon As You Use Them Without The Need Of A Restart</b>      \n\n  ☞ <b>Configure</b> - <b>Button Will Helps You To Change No. of Pages/ Buttons Per Page/ Total Result Without Acutally Editing The Repo... Also It Provide Option To Enable/Disable For Showing Invite Link In Each Results</b> @KOT_BOTS"""
    DYNO_TEXT = """👤Total Users {}\n🧐Total Chtas {}\n🤯Total Manul Filters {}\n🕐Bot Update Time {} @KOT_BOTS"""
    INFORMATION_TEXT = """<b><u>Extra Modes</u></b>\n\n<b>NOTE:</b>\nthese are the extra features of VJ-v2\n\n<b><u>Work Only Group:</u></b>:\n\n• No inline Message\n• No Forword Message\n\n<b><u>CMD Work Only Group:</u></b>\n• /report - report To admin\n\n<b><u>Commands and Usage:</u></b>\n• /id - get id about a user and group.\n• /info  - get information about a user and Group.\n• /status - Get Bot Status @KOT_BOTS"""
    CREDITS_TEXT = """<u><b>DEV</b></u>\n• KOTBOTS\n\n<b><u>TroJanzHEX</u></b>\n• Unlimitedfilter\n<b><u>CrazyBotsz</u></b>\n• ADV AutoFilter V2\n<b><u>Bughunter</u></b>\n• Report\n• Ban\n<b><u>Professor-99</u></b>\n• Broadcast Bot\n• DonLee Robot 2.9 IMDB poster\n• Forword and Inline Delete\n• unban\n• [Refresh Button] VJ\n<b><u>EvamariaTG</u></b>\n• Evamaria IMDB Poster"""
    CONNECTION_TEXT = """<b><u>Connection</u></b>\n\n- Used to connect bot to PM for managing filters \n- it helps to avoid spamming in groups.\n\nNOTE:\n1. Only admins can add a connection.\n2. Send /connect for connecting me to ur PM\n\nCommands and Usage:\n• /connect  - connect a particular chat to your PM\n• /disconnect  - disconnect from a chat\n• /connections - list all your connections"""
    DEV_TEXT = """<b><u>DEVELOPER INFO</b></u>\n\n• TG Name : <a href="t.me/KOT_BOTS">KOT BOTS</a>\n• TG Username : <a href="t.me/KOT_FREE_DE_LA_HOYA_OFF">@KOT_FREE_DE_LA_HOYA_OFF</a>\n• Github : <a href="https://github.com/KOT-BOTS-REPO">KOT BOTS</a>\n• DEVELOPER :  <a href="https://t.me/KOT_DEVELOPERS">KOT DEVELOPER</a> \n• YouTube : <a href="https://youtube.com/channel/UCWBJ4ZVNc4kWoZKp5Y-byHA">KOT BOTS</a> \n• Whatsapp : None\n• Facebook : KOT-BOTS"""
    GROUP_ADMIN_TEXT = """<b><u>Group Commands</u></b>\n\n<b><u>Bot Master</u></b>\n• /broadcast - Replay Any Message\n\n<b><u>Group Admin Only</u></b>\n• /ban - Reply Any User Text\n• /unban - Reply Banned User Text"""
    SUB_TEXT = """ID YOU ARE INTERST IN MAKE THIS BOT CONTACT : @KOT_SOURCE_CODE"""
    SPELLING_TEXT = """Hey {} Check Your Spelling PUT ONLY MOVIE NAME CORRECT"""
    STATUS_TEXT = """<b><u>Bot Status</u></b>\nTotal Users <b>{}</b> @KOT_BOTS"""
    SOURCE_TEXT = """<b><u>🥳 Tʜᴀʟᴀᴘᴀᴛʜʏ Vɪᴊᴀʏ SOURCE CODE</b></u>\n\n📦 REPOSITORY :- https://t.me/KOT_SOURCE_CODE\n📺 FOLLOW ON YOUTUBE :- https://youtube.com/channel/UCWBJ4ZVNc4kWoZKp5Y-byHA\n\n👩‍👩‍👧‍👧 DEVELOPER TEAM <a href="https://t.me/KOT_DEVELOPERS">KOT DEVELOPES</a>"""
